spring:
  datasource:
    ucds:
      username: ucds
      password: ucds
      jdbc-url: jdbc:mysql://10.130.41.12:3306/ucds
      driver-class-name: com.mysql.jdbc.Driver

    business:
      conn-str: 10.130.41.212:30065

    sqlite:
      jdbc-url: jdbc:sqlite:D:/My Work/Java/idea/recordmanager/src/main/db/recordmanager?date_string_format=yyyy-MM-dd HH:mm:ss
      driver-class-name: org.sqlite.JDBC

ccod:
  platformId: shltPA
  platformName: 上海联通平安
  platformType: CLOUD
  buzDBCount: 1
  recordType: MIX
  hasBak: false
  enterprise:
    choseMethod: INCLUDE
    list:
      - "0000099999"
      - "20190423"
      - "0000057722"
      - "0000057733"
      - "0000057744"
      - "0000057755"
    notCheckBakList:

call:
  callTypes:
  endTypes:
  minTalkDuration: 1
  notCheckeEnts:
  notCheckBakEnts:

db:
  gls:
    type: UCDS
  business:
    type: MONGO
    count: 1
    db1Name: db1
  table:
    detail: R_DETAIL
    enterprise: UCD_ENTERPRISE_INFO
    agent: UCD_ENTERPRISE_AGENT_INFO
    mix: ENT_RECORD_TABLE
    combination: ENT_RECORD_BX_TABLE
    bak: ENT_RECORD_BX_TABLE
    dbAgentRelate: GLS_DB_AGENT_RELATE
    dbEntRelate: GLS_DB_ENT_RELATE


record:
  master:
    storeRoles[0]:
      mntDir: "D:/mnt"
      grokPattern: ^D:/mnt/Data/record/(?<entId>\d+)/Agent/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/(?<type>[A-Z]+)-(?<AgentDn>\d+)_(?<agentId>\d+)_(?<remoteUrl>\d+).wav$
      example: D:/mnt/Data/record/0000057733/Agent/20200313/SIP-400503_5860042291_20200317113441.wav
      recordIndex: 0000057733/Agent/20200313/SIP-400503_5860042291_20200317113441.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
    storeRoles[1]:
      mntDir: "/mnt"
      grokPattern: ^/mnt/Date1/(?<entId>\d+)/(?<yearAndMonth>20\d{2}(0[1-9]|1[0-2]))/(?<AgentDn1>\d+)/(?<monthAndDay>(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/(?<type>[A-Z]+)-(?<localUrl>\d+)_(?<agentId>\d+)_(?<remoteUrl>\d+).wav$
      example: /mnt/Date1/0000050111/202003/60750230/0301/SIP-400603_5860042292_20200317123441.wav
      recordIndex: 0000050111/202003/60750230/0301/SIP-400603_5860042292_20200317123441.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
    storeRoles[2]:
      mntDir: "/mnt"
      grokPattern: ^/mnt/record/Data11/save/(?<entId>[a-zA-z0-9]+)/Agent/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/(?<type>[A-Z]+)-(?<AgentDn>\d+)_(?<agentId>\d+)_(?<remoteUrl>\d+).wav$
      example: /mnt/record/Data11/save/JT04/Agent/20200401/TEL-1169190304_100004_20200401081955.wav
      recordIndex: JT04/Agent/20200401/TEL-1169190304_100004_20200401081955.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
  backup:
    storeRoles[0]:
      mntDir: "/mnt"
      grokPattern: ^/mnt/record/Data11/save/(?<entId>[a-zA-z0-9]+)/Agent/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/(?<type>[A-Z]+)-(?<AgentDn>\d+)_(?<agentId>\d+)_(?<remoteUrl>\d+).wav$
      example: /mnt/record/Data11/save/JT04/Agent/20200401/TEL-1169190304_100004_20200401081955.wav
      recordIndex: JT04/Agent/20200401/TEL-1169190304_100004_20200401081955.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd

jobs:
  recordCheck:
    execute: true
    interval: 20
    cron: 0 0/1 * * * ?
    delay: 10
  backup:
    execute: true
    startDate: 2020-01-01
    cron: 0 0/2 * * * ?
    backupRootPath: D:/mnt/backup
    verify: true
    compareWithDB: true
    businessEndTime: "23:00"
    stopTime: "05:00"

notify:
  record-check:
    indexLostCount: 9
    indexLostRate: 10
    fileLostCount: 8
    fileLostRate: 9
    bakIndexLostCount: 7
    bakIndexLostRate: 8
    bakFileLostCount: 6
    bakFileLostRate: 7
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=89c1999c06156510a82bad9d378173086fc2f5faaf7f170f44a8d8f9b8071b54
        tag: "[录音报警]"
        atAll: true
        atList:
          - 18515100747
    sysLog:
      write: true
      tag: "ccod"
  record-backup:
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=89c1999c06156510a82bad9d378173086fc2f5faaf7f170f44a8d8f9b8071b54
        tag: "[录音备份]"
        atAll: true
        atList:
          - 18515100747
    sysLog:
      write: true
      tag: "ccod"

env:
  windows: true

debug: true



