spring:
  datasource:
    gls:
      username: ccod
      password: ccod
      jdbc-url: jdbc:oracle:thin:@172.16.0.94:1521:saas
      driver-class-name: oracle.jdbc.OracleDriver

    business:
      username: ccod
      password: ccod
      jdbc-url: jdbc:oracle:thin:@172.16.0.94:1521:saas
      driver-class-name: oracle.jdbc.OracleDriver

    sqlite:
      jdbc-url: jdbc:sqlite:/home/recordmanager/db/recordmanager?date_string_format=yyyy-MM-dd HH:mm:ss
      driver-class-name: org.sqlite.JDBC

db:
  gls:
    type: GLS
  business:
    type: ORACLE
    count: 1
  table:
    detail: R_DETAIL
    enterprise: GLS_ENTERPRISE_INFO
    mix: ENT_RECORD_TABLE
    combination: ENT_RECORD_BX_TABLE
    bak: ENT_RECORD_BX_TABLE_BAK
    dbAgentRelate: GLS_DB_AGENT_RELATE
    dbEntRelate: GLS_DB_ENT_RELATE

ccod:
  platformId: ltPA
  platformName: 联通大数据
  platformType: NORMAL
  recordType: COMBINATION
  hasBak: true
  enterprise:
    choseMethod: INCLUDE
    list:
      # - "112233"
      # - "00001111"
      # - "0000088888"
      # - "0000066666"
      # - "20180905"
      # - "20180914"
      # - "0000000002"
      # - "1234554321"
      # - "2020031701"
      # - "LTBD2019080201"
      - "TESTYU2"

    notCheckBakList:

call:
  callTypes:
    - 0
    - 1
  endTypes:
    - 254
    - 255
  minTalkDuration: 1

record:
  master:
    storeRules[0]:
      grokPattern: ^/mnt/record/(?<entId>[a-zA-z0-9]+)/Agent/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/[^/]+.wav$
      example: /mnt/record/TESTYU2/Agent/20200526/SIP-10000001_2222222_20200526081051.wav
      recordIndex: record/TESTYU2/Agent/20200526/SIP-10000001_2222222_20200526081051.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
    storeRules[1]:
      grokPattern: ^/mnt/record/(?<entId>[a-zA-z0-9]+)/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/[^/]+.wav$
      example: /mnt/record/TESTYU2/20200526/18610020350_MTMyOTE5NzYzMTY=_057456881482_057456881482_20200526091955.wav
      recordIndex: record/TESTYU2/20200526/18610020350_MTMyOTE5NzYzMTY=_057456881482_057456881482_20200526091955.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
  backup:
    storeRules[0]:
      grokPattern: ^/mnt/record/(?<entId>[a-zA-z0-9]+)/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/[^/]+.wav$
      example: /mnt/record/TESTYU2/20200526/18610020350_MTMyOTE5NzYzMTY=_057456881482_057456881482_20200526091955.wav
      recordIndex: record/TESTYU2/20200526/18610020350_MTMyOTE5NzYzMTY=_057456881482_057456881482_20200526091955.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd

jobs:
  recordCheck:
    execute: true
    cron: 0 0/10 * * * *
    interval: 10
    delay: 10
  backup:
    execute: true
    startDate: 2020-05-25
    cron: 0 23 10 * * *
    backupRootPath: /Data1/recordbak/cs/
    verify: false
    compareWithDB: true
    businessEndTime: "21:00"
    stopTime: "05:00"

notify:
  record-check:
    indexLostCount: 9
    indexLostRate: 10
    fileLostCount: 8
    fileLostRate: 9
    bakIndexLostCount: 7
    bakIndexLostRate: 8
    bakFileLostCount: 6
    bakFileLostRate: 7
    report-normal-result: true
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=3647e0dec9cbfbaa6f0d62d2abc4fa64fde96d8993aa3448b25d85c7990565c9
        tag: "[录音报警]"
        atAll: true
        atList:
      by-script: true
      script-path: /home/recordmanager/sendMsg.sh
    sysLog:
      write: true
      tag: "ccod"
  record-backup:
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=3647e0dec9cbfbaa6f0d62d2abc4fa64fde96d8993aa3448b25d85c7990565c9
        tag: "[录音备份]"
        atAll: true
        atList:
    sysLog:
      write: false
      tag: "ccod"

env:
  windows: false

debug: false

