spring:
  datasource:
    gls:
      username: ccod
      password: ccod
      jdbc-url: jdbc:oracle:thin:@10.130.41.218:32602:ccod
      driver-class-name: oracle.jdbc.OracleDriver

    business:
      username: ccod
      password: ccod
      jdbc-url: jdbc:oracle:thin:@10.130.41.218:32602:ccod
      driver-class-name: oracle.jdbc.OracleDriver
      initial-size: 2
      max-active: 2
      min-idle: 2

    sqlite:
      jdbc-url: jdbc:sqlite:/temp/recordmanager?date_string_format=yyyy-MM-dd HH:mm:ss
      driver-class-name: org.sqlite.JDBC

db:
  gls:
    type: GLS
  business:
    type: ORACLE
    count: 1
  table:
    detail: R_DETAIL
    enterprise: GLS_ENTERPRISE_INFO
    mix: ENT_RECORD_BX_TABLE
    combination: ENT_RECORD_BX_TABLE
    bak: ENT_RECORD_BX_TABLE_BAK
    dbAgentRelate: GLS_DB_AGENT_RELATE
    dbEntRelate: GLS_DB_ENT_RELATE

ccod:
  platformId: zzyd
  platformName: 郑州阳光
  platformType: NORMAL
  recordType: MIX
  hasBak: false
  enterprise:
    choseMethod: INCLUDE
    list:
      - "3711410001"
    notCheckBakList:

call:
  callTypes:
    - 0
    - 1
  endTypes:
    - 254
    - 255
  minTalkDuration: 1

record:
  master:
    storeRules[0]:
      grokPattern: ^D:/mnt/Data/record/(?<entId>\d+)/Agent/(?<date>20\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/(?<type>[A-Z]+)-(?<AgentDn>\d+)_(?<agentId>\d+)_(?<remoteUrl>\d+).wav$
      example: D:/mnt/Data/record/0000057733/Agent/20200313/SIP-400503_5860042291_20200317113441.wav
      recordIndex: 0000057733/Agent/20200313/SIP-400503_5860042291_20200317113441.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd
  backup:
    storeRules[0]:
      grokPattern: ^/mnt/record/record410/(?<entId>[a-zA-z0-9]+)/(?<yearAndMonth>20\d{2}(0[1-9]|1[0-2]))/[^/]+/(?<monthAndDay>(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))/[^/]+.wav$
      example: /mnt/record/record410/0000000018/202004/10086/0415/20200415075510_1271_8025016844987477774_10086.wav
      recordIndex: 0000000018/202004/10086/0415/20200415075510_1271_8025016844987477774_10086.wav
      dateFormat:
        date: yyyyMMdd
        yearAndMonth: yyyyMM
        monthAndDay: MMdd
        year: yyyy
        month: MM
        day: dd

jobs:
  recordCheck:
    execute: true
    cron: 0 0/5 * * * *
    interval: 10
    delay: 10
  backup:
    execute: false
    startDate: 2020-01-12
    cron: 0 0 1 * * *
    backupRootPath: /jiami
    verify: true
    compareWithDB: false
    businessEndTime: "00:01"
    stopTime: "23:59"

notify:
  record-check:
    indexLostCount: 9
    indexLostRate: 10
    fileLostCount: 1
    fileLostRate: 9
    bakIndexLostCount: 7
    bakIndexLostRate: 8
    bakFileLostCount: 6
    bakFileLostRate: 7
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=89c1999c06156510a82bad9d378173086fc2f5faaf7f170f44a8d8f9b8071b54
        tag: "[录音报警]"
        atAll: true
        atList:
    sysLog:
      write: true
      tag: "ccod"
    wechat:
      script-path: /home/recordmanager/config
      script-name: weixin.sh
      log-file: check_record.log
      wechat-tag: 异常
  record-backup:
    dingding:
      group[0]:
        webHookToken: https://oapi.dingtalk.com/robot/send?access_token=89c1999c06156510a82bad9d378173086fc2f5faaf7f170f44a8d8f9b8071b54
        tag: "[录音备份]"
        atAll: true
        atList:
    sysLog:
      write: false
      tag: "ccod"

env:
  windows: false

debug: false

